# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: myprojectbucket00
  CODE_DEPLOY_APPLICATION_NAME: gitaction-app
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: gitaction-release-group

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew --version
          ./gradlew build -x test # 빌드

      - name: Zip build file and deploy sh
        run: |
          mv ./build/libs/shoppingmall-0.0.1-SNAPSHOT.jar ./
          zip buildFile.zip ./scripts/start.sh ./scripts/stop.sh ./appspec.yml ./shoppingmall-0.0.1-SNAPSHOT.jar

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: upload to S3
        run: aws s3 cp --region ${{ env.AWS_REGION }} ./buildFile.zip s3://${{ env.S3_BUCKET_NAME }}/archive/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }}
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name ${{ env.  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}
          --s3-location bucket=${{ env.S3_BUCKET_NAME }},bundleType=zip,key=archive/buildFile.zip
